### PR TITLE
Updates required by aff-4.0

### PR DESCRIPTION
**Pull request by paluh**

### CODE REVIEW

**Comment by paluh** [comment]
Oh sorry - there is also a change in `set` command API included in this PR. I've extended it so it handles write modifiers. I hope it is not a problem...

**Comment by paluh** [comment]
@rightfold Ping...

**Comment by no-longer-on-githu-b** [comment]
I can’t mutate this repo anymore. The company is bankrupt and I no longer have write access. 😬 I’ll check with my former colleagues.

**Comment by paluh** [comment]
@rightfold Do you have any propositions how I should release and maintain this library if I want to extend it further (I'm using it in production)?

**Review by no-longer-on-githu-b — APPROVED** [review]

**Comment by no-longer-on-githu-b** [comment]
Apparently I can still do reviews, but not merging. Very interesting.

**Comment by no-longer-on-githu-b** [comment]
@paluh would it be an idea to have the git url changed in the bower repository?

**Comment by paluh** [comment]
@rightfold Ok, I'm going to prepare new release this weekend and try to publish it on pursuit and packages-set.

**Comment by paluh** [comment]
@rightfold Can I ask for permission to add my license (I want to add BSD license with my attribution) on top of existing one (I'm going to point out specific commit which marks license change)?

**Comment by paluh** [comment]
I'm closing this as I've hard forked this lib and created separate project: https://github.com/paluh/purescript-redis-client

**Pull request closed without merging**
